using UnityEngine;
using UnityEngine.SceneManagement;
using System.Collections;

[RequireComponent(typeof(AudioSource))]
public class MainMenuController : MonoBehaviour
{
    [Header("Audio Settings")]
    [SerializeField] private AudioSource audioSource;
    [Range(0f, 1f)] [SerializeField] private float sfxVolume = 1f;

    [Header("Audio Clips - BGM")]
    [SerializeField] private AudioClip bgmMenu;

    [Header("Audio Clips - SFX")]
    [SerializeField] private AudioClip clickSfx;
    [SerializeField] private AudioClip startSfx;

    // Method untuk auto-setup via Editor Script
    public void SetupAudioClips(AudioClip click, AudioClip start, AudioClip bgm = null)
    {
        clickSfx = click;
        startSfx = start;
        bgmMenu = bgm;
    }

    void Start()
    {
        // Setup AudioSource untuk SFX
        if (audioSource == null) audioSource = GetComponent<AudioSource>();
        if (audioSource == null) audioSource = gameObject.AddComponent<AudioSource>();
        
        audioSource.playOnAwake = false;
        audioSource.spatialBlend = 0f; 
        audioSource.volume = sfxVolume;

        // Mainkan BGM lewat AudioManager
        if (bgmMenu != null)
        {
            if (AudioManager.instance != null)
                AudioManager.instance.PlayBGM(bgmMenu, 0.5f);
            else
            {
                GameObject amGo = new GameObject("AudioManager_AutoGenerated");
                amGo.AddComponent<AudioManager>().PlayBGM(bgmMenu, 0.5f);
            }
        }
    }

    // Fungsi untuk memulai game (dipasang di tombol START JOURNEY)
    public void PlayGame()
    {
        if (audioSource == null) Debug.LogError("AudioSource belum dipasang di Inspector!");
        StartCoroutine(PlayStartAndLoad());
    }

    private IEnumerator PlayStartAndLoad()
    {
        if (audioSource != null && startSfx != null)
        {
            Debug.Log("Memutar Start SFX dengan volume: " + sfxVolume);
            audioSource.PlayOneShot(startSfx, sfxVolume);
            // Memberikan sedikit delay (0.5 detik) agar suara start terdengar sebelum scene pindah
            yield return new WaitForSeconds(0.5f);
        }

        // Memanggil scene perantara bernama "tes"
        SceneManager.LoadScene("tes");
        Debug.Log("Tombol Start ditekan. Berhasil pindah ke scene perantara (tes).");
    }

    // Fungsi untuk keluar dari game (dipasang di tombol QUIT GAME)
    public void ExitGame()
    {
        PlayClickSound();

        // Menutup aplikasi game
        #if UNITY_EDITOR
            UnityEditor.EditorApplication.isPlaying = false;
        #else
            Application.Quit();
        #endif

        Debug.Log("Tombol Quit ditekan. Sistem meminta game untuk ditutup.");
    }

    // Fungsi pembantu jika lo mau nambahin suara klik ke tombol lain (misal: Settings/Options)
    public void PlayClickSound()
    {
        if (audioSource != null && clickSfx != null)
        {
            Debug.Log("Memutar Click SFX");
            audioSource.PlayOneShot(clickSfx, sfxVolume);
        }
        else
        {
            Debug.LogWarning("AudioSource atau AudioClip klik belum diassign!");
        }
    }
}
