using System.Collections;
using TMPro;
using UnityEngine;
using UnityEngine.InputSystem;
using UnityEngine.UI; // for Image UI

public class EndingDialogueManager : MonoBehaviour
{
    [Header("UI")]
    public GameObject dialoguePanel;
    public TextMeshProUGUI dialogueText;

    [Header("Petunjuk Gambar References")]
    public GameObject petunjukSpaceImage;   // Gambar untuk petunjuk Space (saat dialog)
    public GameObject petunjukMoveImage;    // Gambar untuk petunjuk A/D (saat bergerak)
    public GameObject petunjukInteractImage;// Gambar untuk petunjuk E (saat interaksi)

    [Header("White Flash")]
    public SpriteRenderer whiteFlash;

    [Header("Dark Effect")]
    public SpriteRenderer darkOverlay;

    [Header("Characters")]
    public GameObject aren;
    public GameObject luma;

    [Header("Name Box Images")]
    public Image namaImageAren; 
    public Image namaImageLuma; 
    public Image namaImageChild; 
    public Image namaImageShadowInk; 
    public Image namaImageAnakKecil; 

    public GameObject lostChildSad;
    public GameObject lostChildHappy;

    [Header("Shadow")]
    public ShadowInkController shadowInk;

    [Header("Background")]
    public GameObject bgCards;
    public GameObject bgLight;

    [Header("Dialogue")]
    public DialogueLine[] introLines;
    public DialogueLine[] memoryLines;
    public DialogueLine[] shadowLines;

    [Header("Audio Settings")]
    public AudioSource audioSource;
    [Range(0f, 1f)] public float bgmVolume = 0.5f;
    [Range(0f, 1f)] public float sfxVolume = 1f;

    [Header("Audio Clips - BGM")]
    public AudioClip bgmLevel;

    [Header("Audio Clips - SFX")]
    public AudioClip sfxShadowinkMuncul;
    public AudioClip sfxShadowinkHilang;

    public void SetupAudioClips(AudioClip bgm, AudioClip s_muncul, AudioClip s_hilang)
    {
        bgmLevel = bgm;
        sfxShadowinkMuncul = s_muncul;
        sfxShadowinkHilang = s_hilang;
    }

    private int index = 0;

    private enum DialogueState
    {
        Intro,
        Memory,
        Shadow
    }

    private DialogueState currentState;

    // =========================
    // UNITY
    // =========================

    void Start()
    {
        InitializeScene();

        // --- AUDIO SETUP AGRESIF ---
        if (audioSource == null) 
        {
            audioSource = GetComponent<AudioSource>();
            if (audioSource == null) audioSource = GetComponentInChildren<AudioSource>();
            if (audioSource == null) audioSource = gameObject.AddComponent<AudioSource>();
        }
        audioSource.spatialBlend = 0f;

        // Play BGM with Failsafe
        if (bgmLevel != null)
        {
            if (AudioManager.instance != null)
            {
                AudioManager.instance.PlayBGM(bgmLevel, bgmVolume);
            }
            else
            {
                // Jika AudioManager belum ada, buat otomatis
                GameObject amGo = new GameObject("AudioManager_AutoGenerated");
                amGo.AddComponent<AudioManager>().PlayBGM(bgmLevel, bgmVolume);
            }
        }

        StartIntroScene();
        UpdatePetunjuk();
    }

    void Update()
    {
        HandleInput();
    }

    // =========================
    // INITIALIZE
    // =========================

    void InitializeScene()
    {
        dialoguePanel.SetActive(true);
        // Hide all name images at start
        if (namaImageAren != null) namaImageAren.gameObject.SetActive(false);
        if (namaImageLuma != null) namaImageLuma.gameObject.SetActive(false);
        if (namaImageChild != null) namaImageChild.gameObject.SetActive(false);
        if (namaImageShadowInk != null) namaImageShadowInk.gameObject.SetActive(false);

        SetupBackground();

        SetupCharacters();

        SetupEffects();

        SetupSortingOrders();

        // Ensure name images are assigned (fallback find by name)
        // Fallback find name box images if not assigned
        if (namaImageAren == null) {
            var go = GameObject.Find("NamaBox_Aren");
            if (go != null) namaImageAren = go.GetComponent<Image>();
        }
        if (namaImageLuma == null) {
            var go = GameObject.Find("NamaBox_Luma");
            if (go != null) namaImageLuma = go.GetComponent<Image>();
        }
        if (namaImageChild == null) {
            var go = GameObject.Find("NamaBox_Child");
            if (go != null) namaImageChild = go.GetComponent<Image>();
        }
        if (namaImageShadowInk == null) {
            var go = GameObject.Find("NamaBox_ShadowInk");
            if (go != null) namaImageShadowInk = go.GetComponent<Image>();
        }
        if (namaImageAnakKecil == null) {
            var go = GameObject.Find("NamaBox_AnakKecil");
            if (go != null) namaImageAnakKecil = go.GetComponent<Image>();
        }
        if (namaImageShadowInk == null) {
            var go = GameObject.Find("NamaBox_ShadowInk");
            if (go != null) namaImageShadowInk = go.GetComponent<Image>();
        }
    }

    void SetupBackground()
    {
        bgCards.SetActive(true);

        bgLight.SetActive(false);
    }

    void SetupCharacters()
    {
        lostChildSad.SetActive(true);
        // Reset alpha of lostChildSad to 1
        SpriteRenderer srSad = lostChildSad.GetComponent<SpriteRenderer>();
        if (srSad != null)
        {
            Color c = srSad.color;
            c.a = 1f;
            srSad.color = c;
        }

        lostChildHappy.SetActive(false);
        // Reset alpha of lostChildHappy to 1
        SpriteRenderer srHappy = lostChildHappy.GetComponent<SpriteRenderer>();
        if (srHappy != null)
        {
            Color c = srHappy.color;
            c.a = 1f;
            srHappy.color = c;
        }

        shadowInk.gameObject.SetActive(false);
    }

    void SetupEffects()
    {
        // WHITE FLASH

        whiteFlash.gameObject.SetActive(false);

        Color flashColor = whiteFlash.color;

        flashColor.a = 0f;

        whiteFlash.color = flashColor;

        // DARK OVERLAY

        if (darkOverlay != null)
        {
            Color darkColor = darkOverlay.color;

            darkColor.a = 0f;

            darkOverlay.color = darkColor;
        }
    }

    // =========================
    // INPUT
    // =========================

    void HandleInput()
    {
        if (
            Keyboard.current.spaceKey.wasPressedThisFrame ||
            Mouse.current.leftButton.wasPressedThisFrame
        )
        {
            NextDialogue();
        }
    }

    // =========================
    // NEXT DIALOGUE
    // =========================

    void NextDialogue()
    {
        index++;

        switch (currentState)
        {
            case DialogueState.Intro:
                HandleIntroDialogue();
                break;

            case DialogueState.Memory:
                HandleMemoryDialogue();
                break;

            case DialogueState.Shadow:
                HandleShadowDialogue();
                break;
        }
        UpdatePetunjuk();
    }

    // =========================
    // INTRO
    // =========================

    void StartIntroScene()
    {
        currentState = DialogueState.Intro;

        index = 0;

        DisplayLine(introLines[index]);
    }

    void HandleIntroDialogue()
    {
        if (index >= introLines.Length)
        {
            StartMemoryScene();

            return;
        }

        DisplayLine(introLines[index]);

        TriggerIntroEvents();
    }

    void TriggerIntroEvents()
    {
        switch (index)
        {
            case 2:

                StartCoroutine(ChangeSceneTransition());

                break;
        }
    }

    // =========================
    // MEMORY
    // =========================

    void StartMemoryScene()
    {
        currentState = DialogueState.Memory;

        index = 0;

        DisplayLine(memoryLines[index]);
    }

    void HandleMemoryDialogue()
    {
        if (index >= memoryLines.Length)
        {
            StartShadowScene();

            return;
        }

        DisplayLine(memoryLines[index]);

        TriggerMemoryEvents();
    }

    void TriggerMemoryEvents()
    {
        switch (index)
        {
            case 3:

                StartCoroutine(FadeOutChild());

                break;
        }
    }

    // =========================
    // SHADOW
    // =========================

    void StartShadowScene()
    {
        currentState = DialogueState.Shadow;

        index = -1;

        NextDialogue();
    }

    void HandleShadowDialogue()
    {
        if (index >= shadowLines.Length)
        {
            EndDialogue();

            return;
        }

        DisplayLine(shadowLines[index]);

        TriggerShadowEvents();
    }

    void TriggerShadowEvents()
    {
        switch (index)
        {
            // Namun tiba-tiba tinta hitam...

            case 0:

                shadowInk.Appear();
                if (audioSource != null && sfxShadowinkMuncul != null)
                {
                    audioSource.PlayOneShot(sfxShadowinkMuncul, sfxVolume);
                }

                if (darkOverlay != null)
                {
                    StartCoroutine(DarkenBackground());
                }

                break;

            // Suara berat terdengar...

            case 1:

                shadowInk.ChangeAlpha(0.45f);

                break;

            // "Kalian hanya memperlambat..."

            case 2:

                shadowInk.ChangeAlpha(0.8f);

                break;

            // "Apa itu?!"

            case 4:

                shadowInk.StartMoving();

                break;

            // "Dia mulai mendekat."

            case 6:

                shadowInk.FadeOut();
                if (audioSource != null && sfxShadowinkHilang != null)
                {
                    audioSource.PlayOneShot(sfxShadowinkHilang, sfxVolume);
                }

                break;
        }
    }

    // =========================
    // END
    // =========================

    IEnumerator EndAfterFade()
    {
        yield return new WaitForSeconds(2f);

        EndDialogue();
    }

    void EndDialogue()
    {
        dialoguePanel.SetActive(false);
        UpdatePetunjuk();
        UnityEngine.SceneManagement.SceneManager.LoadScene("main_menu");
    }

    // =========================
    // WHITE FLASH
    // =========================

    IEnumerator ChangeSceneTransition()
    {
        whiteFlash.gameObject.SetActive(true);

        SpriteRenderer flash = whiteFlash;

        Color color = flash.color;

        color.a = 0f;

        flash.color = color;

        float duration = 1.5f;

        float timer = 0f;

        // FADE IN

        while (timer < duration)
        {
            timer += Time.deltaTime;

            float t =
                Mathf.SmoothStep(
                    0f,
                    1f,
                    Mathf.Pow(timer / duration, 1.5f)
                );

            color.a =
                Mathf.Lerp(
                    0f,
                    1f,
                    t
                );

            flash.color = color;

            yield return null;
        }

        // SWITCH BG + CHILD

        bgCards.SetActive(false);

        bgLight.SetActive(true);

        lostChildSad.SetActive(false);

        // Reset alpha of lostChildHappy to 1 before showing it
        SpriteRenderer srHappy = lostChildHappy.GetComponent<SpriteRenderer>();
        if (srHappy != null)
        {
            Color c = srHappy.color;
            c.a = 1f;
            srHappy.color = c;
        }

        lostChildHappy.SetActive(true);

        yield return new WaitForSeconds(0.1f);

        timer = 0f;

        // FADE OUT

        while (timer < duration)
        {
            timer += Time.deltaTime;

            float t =
                Mathf.SmoothStep(
                    0f,
                    1f,
                    timer / duration
                );

            color.a =
                Mathf.Lerp(
                    1f,
                    0f,
                    t
                );

            flash.color = color;

            yield return null;
        }

        color.a = 0f;

        flash.color = color;

        whiteFlash.gameObject.SetActive(false);
    }

    // =========================
    // CHILD
    // =========================

    IEnumerator FadeOutChild()
    {
        SpriteRenderer child =
            lostChildHappy.GetComponent<SpriteRenderer>();

        Color color = child.color;

        while (color.a > 0)
        {
            color.a -= Time.deltaTime;

            child.color = color;

            yield return null;
        }

        lostChildHappy.SetActive(false);
    }

    // =========================
    // DARK OVERLAY
    // =========================

    IEnumerator DarkenBackground()
    {
        Color color = darkOverlay.color;

        while (color.a < 0.35f)
        {
            color.a += Time.deltaTime * 0.2f;

            darkOverlay.color = color;

            yield return null;
        }
    }

    // =========================
    // DISPLAY
    // =========================

    void DisplayLine(DialogueLine line)
    {
        if (line.speaker == "")
        {
            dialogueText.text = line.text;
        }
        else
        {
            dialogueText.text =
                line.speaker + ": " + line.text;
            UpdateNameImages(line.speaker);
        }
    }

    // Update name box visibility based on speaker
    void UpdateNameImages(string speaker)
    {
        // Hide all first
        if (namaImageAren != null) namaImageAren.gameObject.SetActive(false);
        if (namaImageLuma != null) namaImageLuma.gameObject.SetActive(false);
        if (namaImageAnakKecil != null) namaImageAnakKecil.gameObject.SetActive(false);
        if (namaImageShadowInk != null) namaImageShadowInk.gameObject.SetActive(false);

        string spk = (speaker ?? "").Trim().ToLower();
        if (spk == "aren")
        {
            if (namaImageAren != null) namaImageAren.gameObject.SetActive(true);
        }
        else if (spk == "luma")
        {
            if (namaImageLuma != null) namaImageLuma.gameObject.SetActive(true);
        }
        else if (spk == "child")
        {
            if (namaImageChild != null) namaImageChild.gameObject.SetActive(true);
        }
        else if (spk == "anak_kecil")
        {
            if (namaImageAnakKecil != null) namaImageAnakKecil.gameObject.SetActive(true);
        }
        else if (spk == "shadow_ink" || spk == "shadow ink")
        {
            if (namaImageShadowInk != null) namaImageShadowInk.gameObject.SetActive(true);
        }
    }

    // === SISTEM SORTING ORDER ===
    void SetupSortingOrders()
    {
        // 1. Backgrounds paling belakang
        SetSortingOrder(bgCards, -50);
        SetSortingOrder(bgLight, -50);

        // 2. Karakter di depan background
        SetSortingOrder(aren, 10);
        SetSortingOrder(luma, 10);
        SetSortingOrder(lostChildSad, 10);
        SetSortingOrder(lostChildHappy, 10);

        // 3. Efek-efek di depan karakter
        if (shadowInk != null)
        {
            SetSortingOrder(shadowInk.gameObject, 20);
        }
        if (darkOverlay != null)
        {
            SetSortingOrder(darkOverlay.gameObject, 30);
        }
        if (whiteFlash != null)
        {
            SetSortingOrder(whiteFlash.gameObject, 100);
        }
    }

    void SetSortingOrder(GameObject obj, int order)
    {
        if (obj == null) return;

        // Coba di parent
        SpriteRenderer sr = obj.GetComponent<SpriteRenderer>();
        if (sr != null)
        {
            sr.sortingOrder = order;
        }

        // Untuk semua children-nya
        SpriteRenderer[] srs = obj.GetComponentsInChildren<SpriteRenderer>(true);
        foreach (SpriteRenderer childSr in srs)
        {
            childSr.sortingOrder = order;
        }
    }

    // === SISTEM PETUNJUK/TIPS ===
    private bool playerDiAreaInteraksi = false;

    public void SetPetunjukInteraksi(bool diArea)
    {
        playerDiAreaInteraksi = diArea;
        UpdatePetunjuk();
    }

    void UpdatePetunjuk()
    {
        // 1. Matikan semua petunjuk gambar terlebih dahulu
        if (petunjukSpaceImage != null) petunjukSpaceImage.SetActive(false);
        if (petunjukMoveImage != null) petunjukMoveImage.SetActive(false);
        if (petunjukInteractImage != null) petunjukInteractImage.SetActive(false);

        // 2. Tentukan state petunjuk yang aktif
        bool dialogAktif = dialoguePanel != null && dialoguePanel.activeSelf;
        bool interactAktif = !dialogAktif && playerDiAreaInteraksi;

        // 3. Aktifkan petunjuk gambar sesuai state
        if (dialogAktif)
        {
            if (petunjukSpaceImage != null) petunjukSpaceImage.SetActive(true);
        }
        else if (interactAktif)
        {
            if (petunjukInteractImage != null) petunjukInteractImage.SetActive(true);
        }
    }
}